name: .NET na dev

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './src'
        dotnet build --configuration Release --output ./output
        popd
        mkdir stop_app
        
    - name: Add app_offline
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "./stop_app/app_offline.htm"
        
    - name: Stop App
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        security: strict
        server-dir: gla/
        local-dir: ./stop_app/
        
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        security: strict
        local-dir: ./src/output/
        server-dir: gla/
        #delete: "true"
        #exclude: "'^logs/' '^README.md'"
