name: .NET na dev test

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Add app_offline
      run: |
        mkdir stop_app
        echo offline > "./stop_app/app_offline.htm"
        
    - name: Stop App
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        security: loose
        server-dir: gla/
        local-dir: ./stop_app/
        log-level: verbose
